"""tests/test_stress_edge_cases.py — Stress-Testing & Nasty Industrial Edge-Cases Suite.

Ruthlessly tests Crucible against:
- Contradictory dimensions & impossible geometry
- Fractional & composite imperial units
- Malformed headers, comment lines, whitespace noise, duplicate SKUs
- Garbage strings, null variants, and unsupported units
- Attribute Gap Intelligence evaluation
"""

import unittest

from app.merging.conflict_resolver import resolve_field
from app.normalization import cleaners, units
from app.parsing.csv_parser import parse_csv_content
from app.schemas.models import (
    Candidate,
    Evidence,
    FieldDecision,
    FieldStatus,
    ProductRecord,
    SourceType,
)
from app.services.gap_analyzer import analyze_product_gaps
from app.services.pipeline import run_pipeline
from app.validation.rules import cross_field_checks, validate_field


class TestStressEdgeCases(unittest.TestCase):
    """Stress tests for extreme industrial edge cases."""

    def test_contradictory_outer_less_than_bore(self):
        """OD (20 mm) < Bore (25 mm) must trigger a physical violation."""
        norm_map = {"bore_diameter": 25.0, "outer_diameter": 20.0, "width": 15.0}
        issues = cross_field_checks(norm_map)
        self.assertIn("outer_diameter", issues)
        self.assertTrue(any("greater than bore" in note for note in issues["outer_diameter"]))

    def test_impossible_geometry_width_exceeds_outer(self):
        """Width (95 mm) > OD (50 mm) must trigger a physical violation."""
        norm_map = {"bore_diameter": 20.0, "outer_diameter": 50.0, "width": 95.0}
        issues = cross_field_checks(norm_map)
        self.assertIn("width", issues)
        self.assertTrue(any("cannot exceed outer diameter" in note for note in issues["width"]))

    def test_fractional_inch_conversions(self):
        """Fractional and mixed-fractional inches must convert with zero math hallucination."""
        test_cases = [
            ("1-1/4\"", 31.75),
            ("1 1/4 in", 31.75),
            ("3/8 in", 9.525),
            ("5/8\"", 15.875),
            ("1/2 in", 12.7),
            ("3/4\"", 19.05),
            ("1/16 in", 1.5875),
        ]
        for raw_str, expected_mm in test_cases:
            val, unit = units.normalize("bore_diameter", raw_str)
            self.assertAlmostEqual(val, expected_mm, places=2, msg=f"Failed for {raw_str}")
            self.assertEqual(unit, "millimeter")

    def test_thousand_separator_force_conversion(self):
        """'14,800 N' and '4750 N' must convert to kN without decimal truncation."""
        val1, u1 = units.normalize("dynamic_load_rating", "14,800 N")
        self.assertAlmostEqual(val1, 14.8, places=2)
        self.assertEqual(u1, "kilonewton")

        val2, u2 = units.normalize("dynamic_load_rating", "4750 N")
        self.assertAlmostEqual(val2, 4.75, places=2)
        self.assertEqual(u2, "kilonewton")

    def test_lbf_to_kilonewton(self):
        """Force in pounds (e.g. 6800 lbf) must convert accurately to kN (~30.25 kN)."""
        val, unit = units.normalize("dynamic_load_rating", "6800 lbf")
        self.assertAlmostEqual(val, 30.248, places=1)
        self.assertEqual(unit, "kilonewton")

    def test_malformed_csv_headers_and_comments(self):
        """CSV parser must tolerate comments, empty lines, and noisy messy headers."""
        raw_csv = """# This is an export comment header
# Generated by ERP on 2026-08-18

  Part #  ,  Bore (d) [mm]  ,  OD (D) mm  ,  Width_B  ,  Mass / Wt (kg)  ,  C_dyn (kN)
6205-TEST , 25 mm           , 52 mm       , 15 mm    , 0.13 kg         , 14.8 kN

# Trailing comments
"""
        rows = parse_csv_content(raw_csv)
        self.assertEqual(len(rows), 1)
        row = rows[0]
        self.assertEqual(row.get("sku"), "6205-TEST")
        self.assertEqual(row.get("bore_diameter"), "25 mm")
        self.assertEqual(row.get("outer_diameter"), "52 mm")
        self.assertEqual(row.get("width"), "15 mm")
        self.assertEqual(row.get("weight"), "0.13 kg")
        self.assertEqual(row.get("dynamic_load_rating"), "14.8 kN")

    def test_garbage_strings_and_null_variants(self):
        """Garbage text and null variations must return (None, None) gracefully."""
        garbage_cases = ["N/A", "none", "NULL", "-", "--", "nil", "unknown", "invalid string ???", ""]
        for g in garbage_cases:
            val, unit = units.normalize("bore_diameter", g)
            self.assertIsNone(val, msg=f"Expected None for garbage string {g!r}")

    def test_duplicate_sku_merging_in_pipeline(self):
        """Duplicate rows for the same SKU must merge candidate claims rather than duplicate products."""
        csv_with_dupes = """sku,bore_diameter,outer_diameter,width
6205-DUP,25 mm,52 mm,15 mm
6205-DUP,25.0 mm,52.0 mm,15.0 mm
"""
        records = run_pipeline(csv_content=csv_with_dupes)
        dup_records = [r for r in records if r.sku == "6205-DUP"]
        self.assertEqual(len(dup_records), 1)
        self.assertEqual(dup_records[0].fields["bore_diameter"].final_value, 25.0)

    def test_source_authority_arbitration_hierarchy(self):
        """Datasheet claim (1.0) must beat Distributor CSV claim (0.60) in conflict resolution."""
        cand_csv = Candidate(
            raw_value="0.25 kg",
            normalized_value=0.25,
            unit="kilogram",
            evidence=Evidence(
                source_name="distributor_dump.csv",
                source_type=SourceType.CSV,
                page=None,
                snippet="Weight: 0.25 kg",
                extraction_confidence=0.85,
            ),
        )
        cand_datasheet = Candidate(
            raw_value="0.13 kg",
            normalized_value=0.13,
            unit="kilogram",
            evidence=Evidence(
                source_name="SKF_datasheet.pdf",
                source_type=SourceType.MANUFACTURER_DATASHEET,
                page=2,
                snippet="Mass = 0.13 kg",
                extraction_confidence=0.99,
            ),
        )
        decision = resolve_field("weight", [cand_csv, cand_datasheet])
        self.assertEqual(decision.final_value, 0.13)
        self.assertEqual(decision.status, FieldStatus.CONFLICT_RESOLVED)
        self.assertIn("SKF_datasheet.pdf", decision.decision_reason)

    def test_attribute_gap_intelligence_analysis(self):
        """Attribute gap intelligence must accurately detect missing attributes and assign severity."""
        test_product = ProductRecord(
            sku="INCOMPLETE-BEARING",
            product_name="Incomplete Test Bearing",
            fields={
                "bore_diameter": FieldDecision(
                    field="bore_diameter", final_value=25.0, status=FieldStatus.VALIDATED,
                    confidence=0.95, candidates=[], validation_notes=[], decision_reason="OK"
                ),
                "dynamic_load_rating": FieldDecision(
                    field="dynamic_load_rating", final_value=None, status=FieldStatus.MISSING,
                    confidence=0.0, candidates=[], validation_notes=[], decision_reason="Missing"
                ),
                "limiting_speed": FieldDecision(
                    field="limiting_speed", final_value=None, status=FieldStatus.MISSING,
                    confidence=0.0, candidates=[], validation_notes=[], decision_reason="Missing"
                ),
            },
            overall_confidence=0.50,
            overall_status=FieldStatus.NEEDS_REVIEW,
        )
        gap_res = analyze_product_gaps(test_product)
        self.assertEqual(gap_res.sku, "INCOMPLETE-BEARING")
        self.assertEqual(gap_res.missing_fields_count, 2)
        self.assertTrue(any(g.field == "dynamic_load_rating" and g.severity == "HIGH" for g in gap_res.gaps))
        self.assertTrue(any(g.field == "limiting_speed" and g.severity == "MEDIUM" for g in gap_res.gaps))


if __name__ == "__main__":
    unittest.main()
